version: '3.8'

services:
  voice_command:
    build: .
    image: levieuxmoulin/voice_command:1.0.0
    container_name: lvm_voice_command
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./logs:/app/logs
    environment:
      - DEVICE_ID=tablette_cuisine_01
      - SERVER_HOST=${SERVER_HOST:-192.168.1.100}
      - SERVER_API_PORT=${SERVER_API_PORT:-8080}
      - SERVER_WS_PORT=${SERVER_WS_PORT:-8081}
    devices:
      - "/dev/snd:/dev/snd"

  nginx:
    image: nginx:alpine
    container_name: lvm_voice_command_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - voice_command

networks:
  default:
    name: lvm_network
